### ISSUE TITLE
Bug: shell completion requires system-wide `rstuf` installation

### ISSUE THREAD

**Issue by lukpueh** [repository-service-tuf/repository-service-tuf-cli#469]
### What happened?

When I run `rstuf`, installed in a **virtual environment**, the following entry is added to my `.zshrc` file:
```bash
# Shell completion configuration for the Click Python package
eval "$(_RSTUF_COMPLETE=zsh_source rstuf)"
```

When I then start a shell session, I get the following error:
```bash
pyenv: rstuf: command not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KAUTH** [comment]
@lukpueh thanks for reporting this! I am assigning this to myself.

**Comment by KAUTH** [comment]
@lukpueh the bug should now be resolved if you update to `auto-click-auto` >= v0.1.3

**Comment by lukpueh** [comment]
Thanks for the patch, @KAUTH! Unfortunately, this still doesn't work for me. Here's the full output I get:
```
pyenv: rstuf: command not found

The `rstuf' command exists in these Python versions:
  3.11.3/envs/rstuf-cli-test
  rstuf-cli-test

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
```

The problem is that I have `rstuf` installed in a `pyenv` virtual environment. This means there is an `rstuf` *shim* on the system path, which redirects to the actual command, but only if I'm in the corresponding. Otherwise it prints this error message, also when running `command -v rstuf`, as `auto-click-auto` does.
